import { PrismaClient,ProductStatus,Role,FuelType,OrderStatus,PromotionScope,PromotionType } from '@prisma/client';import argon2 from 'argon2';
const prisma=new PrismaClient();
const brands=['Toyota','Volkswagen','Ford','BMW','Mercedes-Benz','Audi','Opel','Škoda','Renault','Hyundai'];
const categories=[['Fék','fek'],['Féktárcsa','fektarcsa','fek'],['Fékbetét','fekbetet','fek'],['Szűrők','szurok'],['Motorolaj','motorolaj'],['Futómű','futomu'],['Világítás','vilagitas'],['Akkumulátor','akkumulator'],['Karosszéria','karosszeria'],['Kiegészítők','kiegeszitok']];
async function main(){const hash=await argon2.hash('Demo1234!');for(const [email,role,name] of [['customer@autoparts.local',Role.CUSTOMER,'Vásárló'],['warehouse@autoparts.local',Role.WAREHOUSE,'Raktáros'],['support@autoparts.local',Role.SUPPORT,'Ügyfélszolgálat'],['admin@autoparts.local',Role.ADMIN,'Admin'],['superadmin@autoparts.local',Role.SUPERADMIN,'Szuperadmin']] as const)await prisma.user.upsert({where:{email},update:{},create:{email,passwordHash:hash,firstName:name,lastName:'Demo',role,emailVerifiedAt:new Date()}});
 const catIds:Record<string,string>={};for(const [name,slug,parent] of categories){const c=await prisma.category.upsert({where:{slug},update:{},create:{name,slug,parentId:parent?catIds[parent]:undefined}});catIds[slug]=c.id;}
 const manufacturers=[];for(const name of ['AutoCore','RoadMax','NordParts','BrakeLine','FilterPro','VoltEdge'])manufacturers.push(await prisma.manufacturer.upsert({where:{name},update:{},create:{name}}));
 const engineIds:string[]=[];for(const b of brands){const brand=await prisma.vehicleBrand.upsert({where:{name:b},update:{},create:{name:b}});for(let m=1;m<=2;m++){const mn=`${b} ${m===1?'Compact':'Touring'}`;const model=await prisma.vehicleModel.upsert({where:{brandId_name:{brandId:brand.id,name:mn}},update:{},create:{brandId:brand.id,name:mn}});const gen=await prisma.vehicleGeneration.upsert({where:{modelId_name_yearFrom:{modelId:model.id,name:'2020–',yearFrom:2020}},update:{},create:{modelId:model.id,name:'2020–',yearFrom:2020,bodyStyle:m===1?'hatchback':'wagon'}});for(const [name,code,fuel,power,cc] of [['1.5',`${b.slice(0,2).toUpperCase()}15`,FuelType.PETROL,88,1498],['2.0D',`${b.slice(0,2).toUpperCase()}20D`,FuelType.DIESEL,110,1968]] as const){const e=await prisma.vehicleEngine.upsert({where:{generationId_name:{generationId:gen.id,name}},update:{},create:{generationId:gen.id,name,engineCode:code,fuel,powerKw:power,displacementCc:cc,drivetrain:'FWD',transmission:'6MT'}});engineIds.push(e.id);}}}
 const warehouses=[];for(const w of [{code:'BUD',name:'Budapest központi raktár',address:'Budapest'},{code:'PEST',name:'Pesti átvételi raktár',address:'Budapest'}])warehouses.push(await prisma.warehouse.upsert({where:{code:w.code},update:{},create:w}));
 for(let i=1;i<=50;i++){const sku=`AP-${String(i).padStart(5,'0')}`;const slug=`minta-alkatresz-${i}`;const gross=1990+i*730;const p=await prisma.product.upsert({where:{sku},update:{},create:{name:`${['Prémium fékbetét','Olajszűrő','Levegőszűrő','Féktárcsa','Akkumulátor'][i%5]} ${i}`,slug,sku,ean:`5990000${String(i).padStart(6,'0')}`,shortDescription:'Megbízható, ellenőrzött minőségű demonstrációs autóalkatrész.',description:'AutoParts Pro saját mintatermék. A műszaki adatokat és kompatibilitást demonstrációs célra hoztuk létre.',manufacturerId:manufacturers[i%manufacturers.length].id,netPrice:Math.round(gross/1.27),grossPrice:gross,vatRate:27,purchasePrice:Math.round(gross*0.55),status:ProductStatus.ACTIVE,minStock:3,universal:i%10===0,oemNumbers:[`OEM-${10000+i}`],alternativeNumbers:[`ALT-${20000+i}`],specs:{material:'demo',position:i%2?'front':'rear'},categories:{connect:[{id:catIds[[ 'fektarcsa','fekbetet','szurok','akkumulator','kiegeszitok'][i%5]]}]},images:{create:{url:`http://localhost:3000/product-placeholder.svg`,alt:`AutoParts Pro mintatermék ${i}`,isPrimary:true}}}});for(const w of warehouses)await prisma.inventoryBalance.upsert({where:{productId_warehouseId:{productId:p.id,warehouseId:w.id}},update:{},create:{productId:p.id,warehouseId:w.id,physical:(i*7+w.code.length)%24,reserved:0,damaged:i%13===0?1:0,incoming:i%9===0?5:0}});if(!p.universal&&engineIds.length){for(const engineId of [engineIds[i%engineIds.length],engineIds[(i*3)%engineIds.length]])await prisma.productFitment.upsert({where:{productId_engineId:{productId:p.id,engineId}},update:{},create:{productId:p.id,engineId,notes:'Demonstrációs kompatibilitás'}});}}
 let promo=await prisma.promotion.findFirst({where:{name:'Nyári 10%'}});if(!promo)promo=await prisma.promotion.create({data:{name:'Nyári 10%',type:PromotionType.PERCENT,scope:PromotionScope.CART,value:10,priority:10,startsAt:new Date('2026-08-01'),endsAt:new Date('2026-08-31')}});await prisma.coupon.upsert({where:{code:'NYAR10'},update:{promotionId:promo.id},create:{code:'NYAR10',promotionId:promo.id,minCartGross:10000,globalLimit:500,perUserLimit:1}});
 const customer=await prisma.user.findUniqueOrThrow({where:{email:'customer@autoparts.local'}});const sample=await prisma.product.findMany({take:2});if(!(await prisma.order.findFirst({where:{orderNumber:'AP-DEMO-0001'}})))await prisma.order.create({data:{orderNumber:'AP-DEMO-0001',userId:customer.id,email:customer.email,status:OrderStatus.PROCESSING,subtotalGross:sample.reduce((s,p)=>s+Number(p.grossPrice),0),discountGross:0,shippingGross:1990,totalGross:sample.reduce((s,p)=>s+Number(p.grossPrice),1990),paymentMethod:'cod',shippingMethod:'home',shippingAddress:{postalCode:'1111',city:'Budapest',street:'Minta utca 1.'},billingAddress:{postalCode:'1111',city:'Budapest',street:'Minta utca 1.'},items:{create:sample.map(p=>({productId:p.id,sku:p.sku,productName:p.name,quantity:1,unitNet:p.netPrice,vatRate:p.vatRate,unitGross:p.grossPrice,lineGross:p.grossPrice}))},history:{create:{toStatus:OrderStatus.PROCESSING,actorId:customer.id,customerNote:'Demo rendelés'}}}});
}
main().finally(()=>prisma.$disconnect());
