'use client';
import {FormEvent,useState} from 'react';
import {api} from '../../lib/api';
import {notify} from '../../components/Feedback';

type Role='CUSTOMER'|'WAREHOUSE'|'SUPPORT'|'ADMIN'|'SUPERADMIN';
const demos=[['Vásárló','customer@autoparts.local'],['Raktáros','warehouse@autoparts.local'],['Ügyfélszolgálat','support@autoparts.local'],['Admin','admin@autoparts.local'],['Szuperadmin','superadmin@autoparts.local']] as const;
function destination(role:Role){if(role==='WAREHOUSE')return'/warehouse';if(role==='SUPPORT')return'/admin/orders';if(role==='ADMIN'||role==='SUPERADMIN')return'/admin';return'/products'}
export default function Login(){const[email,setEmail]=useState('customer@autoparts.local');const[password,setPassword]=useState('Demo1234!');const[busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const result=await api<{user:{id:string;email:string;role:Role}}>('/auth/login',{method:'POST',body:JSON.stringify({email,password})});notify('success','Sikeres belépés',`${result.user.email} · ${result.user.role}`);window.dispatchEvent(new CustomEvent('autoparts:cart-updated'));location.href=destination(result.user.role)}catch(err){notify('error','Sikertelen belépés',err instanceof Error?err.message:'Ellenőrizd a belépési adatokat.')}finally{setBusy(false)}}return <main className="section"><div className="container login-layout"><form onSubmit={submit} className="panel stack login-panel"><span className="eyebrow">AutoParts Pro fiók</span><h1>Belépés</h1><p className="muted">Jelentkezz be a vásárlói, raktári vagy admin felülethez.</p><label className="field-label">E-mail<input className="input" name="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label className="field-label">Jelszó<input className="input" name="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button disabled={busy} className="button full-button">{busy?'Belépés…':'Belépés'}</button><div className="demo-credentials"><strong>Lokális demo fiókok</strong><p className="muted">Mindegyik jelszava: <code>Demo1234!</code></p><div className="demo-grid">{demos.map(([label,mail])=><button type="button" className="demo-account" key={mail} onClick={()=>{setEmail(mail);setPassword('Demo1234!')}}><span>{label}</span><small>{mail}</small></button>)}</div></div></form><aside className="login-aside"><span className="eyebrow">Szerepkör alapú rendszer</span><h2>Egy webshop, több munkafolyamat</h2><p>Vásárlóként a katalógus és rendeléseid, raktárosként a komissiózás, adminként pedig a teljes kereskedelmi felület érhető el.</p><div className="security-chip">🔒 HttpOnly cookie-alapú munkamenet</div></aside></div></main>}
