'use client';
import { FormEvent, useEffect, useState } from 'react';
import { api } from '../../../lib/api';

export default function AdminPromotions(){
  const [items,setItems]=useState<any[]>([]),[msg,setMsg]=useState('');
  const load=()=>api<any[]>('/promotions').then(setItems).catch(()=>setItems([]));
  useEffect(()=>{void load()},[]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);await api('/promotions',{method:'POST',body:JSON.stringify({name:f.get('name'),type:f.get('type'),scope:f.get('scope'),value:Number(f.get('value')),priority:Number(f.get('priority')||0),startsAt:f.get('startsAt'),endsAt:f.get('endsAt')||undefined,automatic:true,manufacturerNames:String(f.get('manufacturerNames')||'').split(',').map(x=>x.trim()).filter(Boolean),categorySlugs:String(f.get('categorySlugs')||'').split(',').map(x=>x.trim()).filter(Boolean)})});setMsg('Akció létrehozva.');form.reset();void load()}
  return <main className="section"><div className="container"><h1>Akciók és kuponok</h1><form className="panel stack" onSubmit={create}><input className="input" name="name" placeholder="Akció neve" required/><div className="two"><select className="select" name="type"><option value="PERCENT">Százalék</option><option value="FIXED">Fix összeg</option><option value="FREE_SHIPPING">Ingyenes szállítás</option></select><select className="select" name="scope"><option value="CART">Kosár</option><option value="PRODUCT">Termék</option><option value="CATEGORY">Kategória</option><option value="MANUFACTURER">Gyártó</option></select></div><div className="two"><input className="input" name="value" type="number" min="0" placeholder="Érték" required/><input className="input" name="priority" type="number" placeholder="Prioritás" defaultValue="10"/></div><div className="two"><input className="input" name="startsAt" type="datetime-local" required/><input className="input" name="endsAt" type="datetime-local"/></div><input className="input" name="manufacturerNames" placeholder="Gyártók vesszővel (pl. AutoCore,RoadMax)"/><input className="input" name="categorySlugs" placeholder="Kategória slugok vesszővel"/><button className="button">Automatikus akció létrehozása</button>{msg&&<p>{msg}</p>}</form><div style={{overflowX:'auto',marginTop:24}}><table><thead><tr><th>Név</th><th>Típus</th><th>Hatókör</th><th>Érték</th><th>Prioritás</th><th>Kuponok</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.type}</td><td>{p.scope}</td><td>{Number(p.value)}</td><td>{p.priority}</td><td>{p.coupons?.map((c:any)=>c.code).join(', ')||'—'}</td></tr>)}</tbody></table></div></div></main>
}
