'use client';
import { FormEvent, useEffect, useState } from 'react';
import { API, api } from '../../../lib/api';
export default function AdminProducts(){
  const[products,setProducts]=useState<any[]>([]),[mans,setMans]=useState<any[]>([]),[cats,setCats]=useState<any[]>([]),[msg,setMsg]=useState('');
  const load=()=>api<any[]>('/admin/catalog/products').then(setProducts);
  useEffect(()=>{void load().catch(()=>{});void api<any[]>('/admin/catalog/manufacturers').then(setMans).catch(()=>{});void api<any[]>('/admin/catalog/categories').then(setCats).catch(()=>{})},[]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),gross=Number(f.get('grossPrice'));await api('/products',{method:'POST',body:JSON.stringify({name:f.get('name'),slug:f.get('slug'),sku:f.get('sku'),shortDescription:f.get('name'),description:f.get('name'),manufacturerId:f.get('manufacturerId'),netPrice:Math.round(gross/1.27),grossPrice:gross,vatRate:27,categoryIds:[f.get('categoryId')],oemNumbers:[],alternativeNumbers:[]})});setMsg('Piszkozat termék létrehozva.');void load()}
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('file');if(!(file instanceof File))return;const body=new FormData();body.append('file',file);const r=await fetch(`${API}/files/products`,{method:'POST',credentials:'include',body});if(!r.ok){setMsg(await r.text());return}const up=await r.json();await api(`/products/id/${f.get('productId')}/images`,{method:'POST',body:JSON.stringify({url:up.url,alt:f.get('alt'),isPrimary:true})});setMsg('Kép feltöltve és főképként beállítva.');void load()}
  return <main className="section"><div className="container"><h1>Termékkezelés</h1><div className="two"><form className="panel stack" onSubmit={create}><h2>Új termék</h2><input className="input" name="name" placeholder="Terméknév" required/><input className="input" name="slug" placeholder="slug" required/><input className="input" name="sku" placeholder="SKU" required/><input className="input" name="grossPrice" type="number" placeholder="Bruttó ár" required/><select className="select" name="manufacturerId" required><option value="">Gyártó…</option>{mans.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="select" name="categoryId" required><option value="">Kategória…</option>{cats.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="button">Létrehozás</button></form><form className="panel stack" onSubmit={upload}><h2>Termékkép feltöltése</h2><select className="select" name="productId" required><option value="">Termék…</option>{products.map(x=><option key={x.id} value={x.id}>{x.sku} – {x.name}</option>)}</select><input className="input" name="alt" placeholder="Kép leírása"/><input className="input" name="file" type="file" accept="image/jpeg,image/png,image/webp" required/><button className="button">Kép feltöltése</button><p className="muted">JPG, PNG vagy WebP, legfeljebb 5 MB. A backend a fájl fejlécét is ellenőrzi.</p></form></div>{msg&&<p>{msg}</p>}<div style={{overflowX:'auto',marginTop:24}}><table><thead><tr><th>SKU</th><th>Név</th><th>Státusz</th><th>Ár</th><th>Képek</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.sku}</td><td>{p.name}</td><td>{p.status}</td><td>{Number(p.grossPrice).toLocaleString('hu-HU')} Ft</td><td>{p.images?.length??0}</td></tr>)}</tbody></table></div></div></main>
}
