'use client';
import {useEffect,useState} from 'react';

type Notice={id:number;kind:'success'|'error'|'info';title:string;message?:string};
export function notify(kind:Notice['kind'],title:string,message?:string){if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('autoparts:notify',{detail:{kind,title,message}}))}

export function FeedbackHost(){const[items,setItems]=useState<Notice[]>([]);useEffect(()=>{const onNotice=(event:Event)=>{const detail=(event as CustomEvent<Omit<Notice,'id'>>).detail;const id=Date.now()+Math.random();setItems(old=>[...old,{id,...detail}]);window.setTimeout(()=>setItems(old=>old.filter(x=>x.id!==id)),4200)};window.addEventListener('autoparts:notify',onNotice);return()=>window.removeEventListener('autoparts:notify',onNotice)},[]);return <div className="toast-stack" aria-live="polite">{items.map(item=><div className={`toast toast-${item.kind}`} key={item.id} role={item.kind==='error'?'alert':'status'}><div className="toast-icon">{item.kind==='success'?'✓':item.kind==='error'?'!':'i'}</div><div><strong>{item.title}</strong>{item.message&&<p>{item.message}</p>}</div><button aria-label="Értesítés bezárása" onClick={()=>setItems(old=>old.filter(x=>x.id!==item.id))}>×</button></div>)}</div>}

export function SuccessDialog({open,title,message,orderNumber,onClose}:{open:boolean;title:string;message:string;orderNumber?:string;onClose:()=>void}){if(!open)return null;return <div className="dialog-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="dialog-card" role="dialog" aria-modal="true" aria-labelledby="success-dialog-title"><div className="dialog-success-icon">✓</div><h2 id="success-dialog-title">{title}</h2><p className="muted">{message}</p>{orderNumber&&<div className="order-number"><span>Rendelési szám</span><strong>{orderNumber}</strong></div>}<div className="dialog-actions">{orderNumber&&<a className="button secondary" href="/orders">Rendeléseim</a>}<button className="button" onClick={onClose}>Rendben</button></div></div></div>}
